# Generated by Django 5.1.7 on 2025-03-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='backdrop_img',
            field=models.ImageField(blank=True, null=True, upload_to='backdrop/'),
        ),
    ]
