# Generated by Django 5.1.7 on 2025-03-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='albums/'),
        ),
    ]
