# Generated by Django 5.1.7 on 2025-03-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_album_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='albums/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file_url',
            field=models.FileField(blank=True, null=True, upload_to='songs/'),
        ),
    ]
