# Generated by Django 5.1.7 on 2025-03-18 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_album_cover_image_alter_song_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
    ]
