# Generated by Django 5.1.7 on 2025-03-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_remove_album_genre_song_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='explicit',
        ),
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='songs/covers/'),
        ),
    ]
