# Generated by Django 5.1.7 on 2025-03-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_remove_song_explicit_song_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='playlist/'),
        ),
    ]
