# Generated by Django 5.1.7 on 2025-03-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_playlist_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ManyToManyField(to='music.genre'),
        ),
    ]
