# Generated by Django 5.1.7 on 2025-03-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_remove_song_duration_remove_song_genre_song_genre'),
        ('users', '0003_remove_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistsong',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='playlistsong',
            name='song',
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='music.song'),
        ),
        migrations.AddField(
            model_name='song',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborations', to='users.artist'),
        ),
        migrations.DeleteModel(
            name='Collaboration',
        ),
        migrations.DeleteModel(
            name='PlaylistSong',
        ),
    ]
